'use strict';
let project,roomIndex=0,selected=0,mode='objects',polyIndex=0,drag=null,history=[],dirty=false;
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),images=new Map();
const room=()=>project.rooms[roomIndex],object=()=>room().objects[selected],clone=x=>JSON.parse(JSON.stringify(x));
function message(t,error=false){$('status').textContent=t;$('status').style.borderColor=error?'#c77869':'#b59a70'}
function checkpoint(){history.push(JSON.stringify(project));if(history.length>40)history.shift();dirty=true}
function asset(name){if(!name)return null;if(!images.has(name)){const im=new Image();im.onload=draw;im.src='/assets/'+name+'.png';images.set(name,im)}return images.get(name)}
function pos(e){const b=canvas.getBoundingClientRect();return{x:Math.round((e.clientX-b.left)*640/b.width),y:Math.round((e.clientY-b.top)*352/b.height)}}
function draw(){if(!project)return;ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,640,352);const bg=asset(room().background);if(bg?.complete&&bg.naturalWidth)ctx.drawImage(bg,0,0,640,352);
 const sorted=room().objects.map((o,i)=>({o,i})).sort((a,b)=>(a.o.layer-b.o.layer)||(a.o.y+a.o.height-b.o.y-b.o.height));
 for(const {o,i} of sorted){const im=asset(o.asset);ctx.save();ctx.globalAlpha=o.opacity/100;ctx.translate(o.x+o.width/2,o.y+o.height/2);ctx.rotate(o.rotation*Math.PI/180);if(o.flip)ctx.scale(-1,1);if(im?.complete&&im.naturalWidth){if(o.tint!=='#ffffff'){const off=document.createElement('canvas');off.width=o.width;off.height=o.height;const oc=off.getContext('2d');oc.imageSmoothingEnabled=false;oc.drawImage(im,0,0,o.width,o.height);oc.globalCompositeOperation='multiply';oc.fillStyle=o.tint;oc.fillRect(0,0,o.width,o.height);oc.globalCompositeOperation='destination-in';oc.drawImage(im,0,0,o.width,o.height);ctx.drawImage(off,-o.width/2,-o.height/2)}else ctx.drawImage(im,-o.width/2,-o.height/2,o.width,o.height)}ctx.restore();if(mode==='objects'&&(i===selected||!o.asset)){ctx.strokeStyle=i===selected?'#edcc91':'#779aa27f';ctx.setLineDash(o.asset?[]:[4,4]);ctx.strokeRect(o.x,o.y,o.width,o.height);ctx.setLineDash([]);if(i===selected){ctx.fillStyle='#edcc91';ctx.fillRect(o.x+o.width-3,o.y+o.height-3,7,7);ctx.strokeStyle='#94cfd0';ctx.beginPath();ctx.moveTo(o.walk[0]-5,o.walk[1]);ctx.lineTo(o.walk[0]+5,o.walk[1]);ctx.moveTo(o.walk[0],o.walk[1]-5);ctx.lineTo(o.walk[0],o.walk[1]+5);ctx.stroke()}}}
 if(mode==='floor'){room().floor.forEach((poly,i)=>{ctx.beginPath();poly.forEach(([x,y],j)=>j?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fillStyle=i===polyIndex?'#60c7b740':'#73b9c220';ctx.fill();ctx.strokeStyle=i===polyIndex?'#91e0c9':'#5e8894';ctx.stroke();poly.forEach(([x,y],j)=>{ctx.fillStyle=i===polyIndex?'#c8f7dc':'#608390';ctx.fillRect(x-3,y-3,6,6);ctx.font='10px monospace';ctx.fillText(j+1,x+6,y-5)})})}
}
function field(key,label,type='number',wide=false){const o=object(),l=document.createElement('label');l.textContent=label;if(wide)l.className='wide';let inp=document.createElement('input');inp.type=type;inp.value=o[key]??'';if(type==='checkbox')inp.checked=!!o[key];inp.onchange=()=>{checkpoint();o[key]=type==='number'?Number(inp.value):type==='checkbox'?inp.checked:inp.value;render()};l.append(inp);$('fields').append(l)}
function render(){const r=room();$('roomName').textContent=r.name;$('objects').replaceChildren();r.objects.forEach((o,i)=>{const b=document.createElement('button');b.textContent=o.name;b.className=i===selected?'selected':'';b.onclick=()=>{selected=i;render()};$('objects').append(b)});$('polygon').replaceChildren();r.floor.forEach((p,i)=>$('polygon').add(new Option('Polygon '+(i+1)+' · '+p.length+' vertices',i)));$('polygon').value=polyIndex;
 $('fields').replaceChildren();const o=object();$('selectedName').textContent=o?.name||'No object';$('selection').textContent=mode==='floor'?'Edit walkable area':o?'Edit '+o.name:'Select an object';$('inspector').hidden=!o;
 if(o){field('name','Name','text',true);field('x','X');field('y','Y');field('width','Width');field('height','Height');field('rotation','Rotation °');field('opacity','Opacity %');field('tint','Tint','color');field('layer','Layer (positive = front)');field('flip','Flip horizontally','checkbox');field('pickup','Pickup flag','checkbox');
 const a=document.createElement('label');a.className='wide';a.textContent='Sprite';const select=document.createElement('select');['','desk','chair','terminal','padd','baseball','console','table','fabric','plant','garak','sisko'].forEach(s=>select.add(new Option(s||'Invisible hotspot',s)));select.value=o.asset;select.onchange=()=>{checkpoint();o.asset=select.value;render()};a.append(select);$('fields').append(a);
 for(let j=0;j<2;j++){const l=document.createElement('label');l.textContent='Approach '+(j?'Y':'X');const inp=document.createElement('input');inp.type='number';inp.value=o.walk[j];inp.onchange=()=>{checkpoint();o.walk[j]=Number(inp.value);draw()};l.append(inp);$('fields').append(l)}
 const e=document.createElement('label');e.className='wide';e.textContent='Exit to';const es=document.createElement('select');es.add(new Option('Not an exit',''));project.rooms.forEach(r=>es.add(new Option(r.name,r.id)));es.value=o.exit||'';es.onchange=()=>{checkpoint();o.exit=es.value;render()};e.append(es);$('fields').append(e);$('actions').value=JSON.stringify(o.actions,null,2)}
 $('dialogues').value=JSON.stringify(project.dialogues,null,2);draw()}
canvas.onpointerdown=e=>{const p=pos(e);if(e.button!==0)return;canvas.setPointerCapture(e.pointerId);if(mode==='floor'){const poly=room().floor[polyIndex];const i=poly?.findIndex(([x,y])=>Math.hypot(x-p.x,y-p.y)<9);if(i>=0){checkpoint();drag={type:'vertex',i}}return}const o=object();if(o&&Math.hypot(p.x-o.x-o.width,p.y-o.y-o.height)<11){checkpoint();drag={type:'resize'};return}let hit=-1;room().objects.forEach((o,i)=>{if(p.x>=o.x&&p.x<=o.x+o.width&&p.y>=o.y&&p.y<=o.y+o.height)hit=i});if(hit>=0){selected=hit;checkpoint();drag={type:'move',dx:p.x-object().x,dy:p.y-object().y};render()}};
canvas.onpointermove=e=>{if(!drag)return;const p=pos(e),o=object();if(drag.type==='vertex')room().floor[polyIndex][drag.i]=[Math.max(0,Math.min(639,p.x)),Math.max(0,Math.min(351,p.y))];else if(drag.type==='resize'){o.width=Math.max(4,Math.min(640,p.x-o.x));o.height=Math.max(4,Math.min(352,p.y-o.y))}else{o.x=Math.max(0,Math.min(639,p.x-drag.dx));o.y=Math.max(0,Math.min(351,p.y-drag.dy))}draw()};canvas.onpointerup=()=>{drag=null;render()};canvas.onpointercancel=()=>{drag=null};
canvas.ondblclick=e=>{if(mode!=='floor')return;const p=pos(e),poly=room().floor[polyIndex];if(!poly)return;let best=Infinity,idx=0;poly.forEach((a,i)=>{const b=poly[(i+1)%poly.length],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((p.x-a[0])*dx+(p.y-a[1])*dy)/(dx*dx+dy*dy)));const d=Math.hypot(p.x-a[0]-t*dx,p.y-a[1]-t*dy);if(d<best){best=d;idx=i+1}});checkpoint();poly.splice(idx,0,[p.x,p.y]);render()};
canvas.oncontextmenu=e=>{e.preventDefault();if(mode!=='floor')return;const p=pos(e),poly=room().floor[polyIndex],i=poly.findIndex(([x,y])=>Math.hypot(x-p.x,y-p.y)<9);if(i>=0&&poly.length>3){checkpoint();poly.splice(i,1);render()}};
function setMode(m){mode=m;$('objectsMode').classList.toggle('active',m==='objects');$('floorMode').classList.toggle('active',m==='floor');$('objectPanel').hidden=m!=='objects';$('floorPanel').hidden=m!=='floor';render()}
$('objectsMode').onclick=()=>setMode('objects');$('floorMode').onclick=()=>setMode('floor');$('polygon').onchange=e=>{polyIndex=Number(e.target.value);draw()};$('room').onchange=e=>{roomIndex=Number(e.target.value);selected=0;polyIndex=0;render()};
$('addPoly').onclick=()=>{checkpoint();room().floor.push([[60,280],[180,280],[180,340],[60,340]]);polyIndex=room().floor.length-1;render()};$('deletePoly').onclick=()=>{if(room().floor.length<2){message('Keep at least one walkable polygon.',true);return}checkpoint();room().floor.splice(polyIndex,1);polyIndex=0;render()};
function newId(){let n=1;const ids=project.rooms.flatMap(r=>r.objects.map(o=>o.id));while(ids.includes('prop_'+n))n++;return 'prop_'+n}
$('add').onclick=()=>{checkpoint();room().objects.push({id:newId(),name:'New object',asset:'padd',x:100,y:230,width:26,height:32,rotation:0,flip:false,tint:'#ffffff',opacity:100,walk:[130,320],layer:0,actions:[{verb:'Look at',text:'A new object.',requires:[],sets:[]}]});selected=room().objects.length-1;render()};
$('duplicate').onclick=()=>{if(!object())return;checkpoint();const o=clone(object());o.id=newId();o.name+=' copy';o.x+=20;o.y+=10;delete o.pickup;room().objects.push(o);selected=room().objects.length-1;render()};$('delete').onclick=()=>{if(!object())return;const id=object().id;if(['padd','garak','display','terminal'].includes(id)){message('This object is required by Chapter 1. Edit its properties and rules instead.',true);return}checkpoint();room().objects.splice(selected,1);selected=Math.max(0,selected-1);render()};
$('undo').onclick=()=>{if(history.length){project=JSON.parse(history.pop());roomIndex=Math.min(roomIndex,project.rooms.length-1);selected=Math.min(selected,room().objects.length-1);render();message('Undone.')}};
$('applyActions').onclick=()=>{try{const a=JSON.parse($('actions').value);if(!Array.isArray(a))throw Error('Expected an array of rules');checkpoint();object().actions=a;message('Interaction changes applied. Save & build to update the game.')}catch(e){message(e.message,true)}};
$('applyDialogues').onclick=()=>{try{const a=JSON.parse($('dialogues').value);if(!a||Array.isArray(a)||typeof a!=='object')throw Error('Expected a dialogue object');checkpoint();project.dialogues=a;message('Dialogue changes applied. Save & build to update the game.')}catch(e){message(e.message,true)}};
$('build').onclick=async()=>{const b=$('build');b.disabled=true;message('Validating walkable areas and compiling the ScummVM game…');try{const r=await fetch('/api/build',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(project)}),d=await r.json();if(!r.ok)throw Error(d.error);dirty=false;message('Built successfully · '+Math.round(d.bytes/1024)+' KB · Open game/chapter1.slg in ScummVM.')}catch(e){message(e.message,true)}finally{b.disabled=false}};
$('export').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}));a.href=url;a.download='project.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('import').onchange=async e=>{try{const p=JSON.parse(await e.target.files[0].text());if(p.schema!==1||!Array.isArray(p.rooms)||!p.settings||!p.dialogues)throw Error('Not a valid Pale Moonlight project');checkpoint();project=p;setup();message('Imported. Save & build validates the project.')}catch(e){message(e.message,true)}};
$('applyFlags').onclick=()=>{try{const a=JSON.parse($('flags').value);if(!Array.isArray(a)||a.some(f=>! /^[a-z][a-z0-9_]*$/.test(f)))throw Error('Use an array of lowercase flag names');checkpoint();project.flags=a;message('Flags updated.')}catch(e){message(e.message,true)}};
function setup(){ $('flags').value=JSON.stringify(project.flags,null,2);roomIndex=0;selected=0;polyIndex=0;$('room').replaceChildren();project.rooms.forEach((r,i)=>$('room').add(new Option(r.name,i)));$('chapters').replaceChildren();project.chapters.forEach(c=>{const li=document.createElement('li');li.textContent=c.title+' · '+c.status;$('chapters').append(li)});$('settings').replaceChildren();for(const [k,v]of Object.entries(project.settings)){const l=document.createElement('label');l.textContent=k;const i=document.createElement('input');i.type='number';i.value=v;i.onchange=()=>{checkpoint();project.settings[k]=Number(i.value)};l.append(i);$('settings').append(l)}render()}
window.onbeforeunload=e=>{if(dirty){e.preventDefault();e.returnValue=''}};
fetch('/project.json').then(r=>{if(!r.ok)throw Error('Start the editor with python tools/studio.py');return r.json()}).then(p=>{project=p;setup();message('Ready. Changes stay local until Save & build.')}).catch(e=>message(e.message,true));
